"""Research-pipeline lifecycle labels and live-promotion enforcement."""

from domain.research.lifecycle import (
    EXPERIMENTS,
    FORBIDDEN_AUTO_PROMOTE,
    GATE_CHECKLIST,
    GateKind,
    GateReceipt,
    IN_FLIGHT_EXPERIMENT_IDS,
    LifecycleLabel,
    REQUIRED_LIVE_GATES,
    ShadowCandidate,
    ShadowExperiment,
    derive_lifecycle_label,
    experiment_by_id,
    in_flight_experiments,
    parse_lifecycle_label,
    receipts_from_shadow_calibration,
)
from domain.research.promotion import (
    LIVE_SHADOW_PROMOTION_ENABLED,
    PromotionBlocked,
    PromotionDecision,
    apply_shadow_impact_to_score,
    assert_live_recommendation_write_allowed,
    authorize_live_shadow_write,
    evaluate_promotion,
    overlay_shadow_on_live_score,
    promote_shadow_candidate_to_live,
    seal_shadow_live_fields,
)

__all__ = [
    "EXPERIMENTS",
    "FORBIDDEN_AUTO_PROMOTE",
    "GATE_CHECKLIST",
    "GateKind",
    "GateReceipt",
    "IN_FLIGHT_EXPERIMENT_IDS",
    "LIVE_SHADOW_PROMOTION_ENABLED",
    "LifecycleLabel",
    "REQUIRED_LIVE_GATES",
    "PromotionBlocked",
    "PromotionDecision",
    "ShadowCandidate",
    "ShadowExperiment",
    "apply_shadow_impact_to_score",
    "assert_live_recommendation_write_allowed",
    "authorize_live_shadow_write",
    "derive_lifecycle_label",
    "evaluate_promotion",
    "experiment_by_id",
    "in_flight_experiments",
    "overlay_shadow_on_live_score",
    "parse_lifecycle_label",
    "promote_shadow_candidate_to_live",
    "receipts_from_shadow_calibration",
    "seal_shadow_live_fields",
]
